[project]
name = "zenodo-rdm-app"
version = "27.0.0rc1"
authors = [
    { name = "CERN" }
]
license = "GPL-3.0-or-later"
requires-python = "~=3.14.0"
dependencies = [
    "invenio-app-rdm[opensearch2,profiler]==15.0.0b3.dev0",
    "zenodo-legacy",
    "zenodo-rdm",
    "github3.py>=3.0.0",
    "nameparser>=1.1.1",
    "pyinstrument>=5.0.0,<6",
    "sqltap>=0.3.11,<1.0.0",
    "zammad-py>=3.0.0,<4.0.0",
    "pyvips>=2.2.2,<3.0.0",
    "invenio-swh",
    "uwsgi>=2.0",
    "uwsgitop>=0.11",
    "uwsgi-tools>=1.1.1",
    "invenio-records-resources",
    "invenio-github>=7.0.0,<8.0.0",
    "invenio-rdm-records",
    # React18
    "invenio-administration",
    "invenio-search-ui",
    "invenio-collections",
    "invenio-communities",
    "invenio-assets",
    "invenio-vocabularies",
    "invenio-requests",
    "invenio-jobs",
    # "react-searchkit",
    # "react-invenio-forms",
]

[tool.uv.sources]
zenodo-rdm = { workspace = true }
zenodo-legacy = { workspace = true }
invenio-swh = { git = "https://github.com/inveniosoftware/invenio-swh", rev = "v0.13.5" }
# User profile fixes
invenio-records-resources = { git = "https://github.com/inveniosoftware/invenio-records-resources", branch = "fix-read-many" }
# Python 3.14 + xrootdpyfs 3.x support (inveniosoftware/invenio-xrootd#40)
invenio-xrootd = { git = "https://github.com/ntarocco/invenio-xrootd", branch = "upgrade-xrootdpyf" }

# React18
invenio-app-rdm = { git = "https://github.com/olivergeneser/invenio-app-rdm", branch = "react-18-migration" }
invenio-rdm-records = { git = "https://github.com/olivergeneser/invenio-rdm-records", branch = "react-18-migration" }
invenio-administration = { git = "https://github.com/olivergeneser/invenio-administration", branch = "react-18-migration" }
invenio-search-ui = { git = "https://github.com/olivergeneser/invenio-search-ui", branch = "react-18-migration"}
invenio-collections = { git = "https://github.com/olivergeneser/invenio-collections", branch = "react-18-migration"}
invenio-communities = { git = "https://github.com/olivergeneser/invenio-communities", branch = "react-18-migration"}
invenio-assets = { git = "https://github.com/olivergeneser/invenio-assets", branch = "react-18-migration"}
invenio-vocabularies = { git = "https://github.com/olivergeneser/invenio-vocabularies", branch = "react-18-migration"}
invenio-requests = { git = "https://github.com/olivergeneser/invenio-requests", branch = "react-18-migration"}
invenio-jobs = { git = "https://github.com/olivergeneser/invenio-jobs", branch = "react-18-migration"}
#react-searchkit = { path = "../react-searchkit" }
#react-invenio-forms = { path = "../react-invenio-forms" }

[tool.uv.workspace]
members = [
    "site",
    "legacy",
]

[dependency-groups]
dev = [
    "pytest-invenio>=3.0.0,<4.0.0",
    "pytest-mock>=1.6.0",
]

[project.optional-dependencies]
sentry = [
    "invenio-logging[sentry]",
]
xrootd = [
    "invenio-xrootd",
    "requests-kerberos==0.14.0",
    "xrootd==5.9.6",
]
