# SPDX-FileCopyrightText: 2016-2025 CERN
# SPDX-FileCopyrightText: 2022 Graz University of Technology
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
    branches:
      - master
      - "feature/*"
  pull_request:
    branches:
      - master
      - "feature/*"
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ["3.14"]
          db-service: [postgresql14]
          search-service: [opensearch2]
    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache Docker images
        # We're using the fork by AndreKurait, which has bumped the "cache" action
        uses: AndreKurait/docker-cache@7a3887908bdb97935395833df69b060cfcca0f7f  # 0.7.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-services.yml') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          activate-environment: true

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@681749ae568c81c2037cb9185e38b709b261bd2f  # v1.6.1
        with:
          packages: libkrb5-dev libvips-dev

      - name: Install Python dependencies
        run: |
          uv sync --locked
          uv pip list

      - name: Run tests
        working-directory: ./site
        run: ./run-tests.sh

  JS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Node.js v24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run eslint test
        run: ./run-js-linter.sh -i

